version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
deploy: off
configuration: Release
platform: Any CPU
services:
  - postgresql
  - mssql2012sp1

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

install:
  - cmd: git submodule update --init --recursive

build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build .\ServiceBase.IdentityServer.sln --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - bash coveralls.sh
