version: 1.2.{build}
branches:
  only:
  - release
  - master
image: Ubuntu
branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/
configuration: Release
platform: x64
clone_script:
- sh: sh ./appveyor-build.sh
build_script:
- sh: sh ./appveyor-build.sh
test_script:
- sh: sh ./appveyor-test.sh
deploy_script:
- sh: sh ./appveyor-deploy.sh