version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
deploy: off
configuration: Release
platform: Any CPU
services: mssql2012sp1

branches:
  only:
  - release
  - master

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: dotnet restore --no-cache

build:
  project: ServiceBase.IdentityServer.sln
  verbosity: minimal

test_script:
- cmd: >-
    bash coverage.sh
    bash coveralls.sh