version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
deploy: off
configuration: Release
platform: Any CPU
services: mssql2012sp1

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: dotnet restore --no-cache

build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - bash coverage.sh
  - bash coveralls.sh

deploy: off