version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
services:
  - mssql2014
  - postgresql

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

install:
  - git submodule update --init --recursive
  
before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build ./IdentityBase.sln -c Release /property:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - nuget pack ./src/IdentityBase/IdentityBase.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/IdentityBase.Public/IdentityBase.Public.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  - nuget pack ./src/IdentityBase.Public.EntityFramework/IdentityBase.Public.EntityFramework.nuspec -OutputDirectory ./artifacts/packages -version %APPVEYOR_BUILD_VERSION%
  
test_script:
  - bash coveralls.sh
  
artifacts:
  - path: artifacts\**\*.*
  
cache:
  - '%USERPROFILE%\.nuget\packages'