version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
deploy: off
configuration: Release
platform: Any CPU

services:
  - mssql2014
  - postgresql

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

install:
  - bash init.sh

build_script:
  - bash build.sh
  - bash pack.sh

test_script:
  - bash coveralls.sh
