version: "2.0"

services:

  # https://hub.docker.com/_/postgres/
  postgres:  
    container_name: idbase-postgres
    image: postgres:9.6.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=root
