version: "2.0"

services:
  
  # https://hub.docker.com/_/rabbitmq/  
  rabbitmq:
    container_name: idbase-rabbitmq
    restart: unless-stopped
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/